require 'rails_helper'

RSpec.describe Project, type: :model do
  describe 'associations' do
    it 'has many project_members' do
      association = described_class.reflect_on_association(:project_members)
      expect(association.macro).to eq :has_many
      expect(association.options).to include(dependent: :destroy)
    end

    it 'has many members' do
      association = described_class.reflect_on_association(:members)
      expect(association.macro).to eq :has_many
      expect(association.options).to include(:through)
      expect(association.options[:through]).to eq :project_members
    end
  end

  describe 'validations' do
    let!(:project) { Fabricate(:project) }

    it 'is valid with default fabricator' do
      expect(project).to be_valid
    end

    it 'is invalid if name is not present' do
      project.name = nil
      expect(project).not_to be_valid
    end

    it 'is invalid if name and slug is not unique' do
      # slug is auto generated by parameterizing name
      invalid_project = described_class.new(name: project.name)

      expect(invalid_project).to be_invalid
      expect(invalid_project.errors.full_messages).to eq(['Name has already been taken', 'Slug has already been taken'])
    end
  end

  describe 'callbacks' do
    context '#generate_slug' do
      let!(:project) { Fabricate(:project, name: 'Test Name 1') }

      it 'generates slug for the project' do
        expect(project.slug).to eq('test-name-1')
      end
    end
  end
end
